services:
  postgres-db:
    pull_policy: always
    container_name: postgres-db
    platform: linux/amd64
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=metalor
    ports:
      - "5432:5432"
    volumes:
      - ./sql/create-db.sql:/docker-entrypoint-initdb.d/create-db.sql
      - ./db:/var/lib/postgresql/data
