spring:
  datasource:
    url: jdbc:postgresql://[::1]:5432/postgres?user=postgres&password=sunday
    driver-class-name: org.postgresql.Driver
    maximum-pool-size: 10
    minimum-idle: 10

logging:
  config: classpath:logback-local.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
mailer:
  sendinblue:
    templateIds:
      EN: 360
